#!/bin/bash

next_ver=$(git tag -l | tail -n1 | awk -F'.' '{printf $1"."$2+1}')

sed -i "s_^version: .*\$_version: ${next_ver}_" _config.yml

git add _config.yml
git commit -m "Publish $next_ver"
git tag $next_ver

cat <<EOF
Recent tags:
$(git tag -n | tail -n5)
EOF
